# Battery Profiles Configuration
# Defines voltage curves and characteristics for different battery types

# Standard 18650 Lithium-Ion Battery
18650_standard:
  chemistry: "Li-ion"
  nominal_voltage: 3.7
  full_voltage: 4.2
  empty_voltage: 2.5
  capacity_mah: 2500
  series_cells: 1
  parallel_groups: 1
  
  # Voltage curve mapping (percentage -> voltage)
  voltage_curve:
    100: 4.20  # Full charge
    95:  4.15
    90:  4.10
    85:  4.05
    80:  4.00
    75:  3.95
    70:  3.90
    65:  3.85
    60:  3.80
    55:  3.78
    50:  3.75  # Nominal voltage
    45:  3.73
    40:  3.70
    35:  3.68
    30:  3.65
    25:  3.62
    20:  3.60
    15:  3.58
    10:  3.55
    5:   3.50
    0:   2.50  # Protection cutoff
    
  # Discharge rate characteristics (current_ma -> capacity_factor)
  discharge_curve:
    250:  1.00   # C/10 rate
    500:  0.98   # C/5 rate
    1000: 0.95   # C/2.5 rate
    2000: 0.90   # C/1.25 rate
    2500: 0.85   # 1C rate
    
  # Temperature compensation
  temperature_coefficients:
    coefficient: -0.003  # -3mV per °C
    reference_temp: 25.0 # Reference temperature in °C
    
  # Safety limits
  safety_limits:
    max_voltage: 4.25
    min_voltage: 2.0
    max_current: 10000   # 10A maximum
    max_temperature: 60.0

# High Capacity 18650 (3500mAh)
18650_high_capacity:
  chemistry: "Li-ion"
  nominal_voltage: 3.7
  full_voltage: 4.2
  empty_voltage: 2.5
  capacity_mah: 3500
  series_cells: 1
  parallel_groups: 1
  
  voltage_curve:
    100: 4.20
    95:  4.16
    90:  4.08
    85:  4.02
    80:  3.98
    75:  3.93
    70:  3.88
    65:  3.83
    60:  3.78
    55:  3.75
    50:  3.73  # More stable plateau
    45:  3.70
    40:  3.68
    35:  3.65
    30:  3.63
    25:  3.60
    20:  3.58
    15:  3.55
    10:  3.53
    5:   3.48
    0:   2.50
    
  discharge_curve:
    350:  1.00
    700:  0.98
    1400: 0.95
    2800: 0.88
    3500: 0.82
    
  temperature_coefficients:
    coefficient: -0.003
    reference_temp: 25.0
    
  safety_limits:
    max_voltage: 4.25
    min_voltage: 2.0
    max_current: 15000
    max_temperature: 60.0

# 21700 Lithium-Ion Battery
21700_standard:
  chemistry: "Li-ion"
  nominal_voltage: 3.7
  full_voltage: 4.2
  empty_voltage: 2.5
  capacity_mah: 4000
  series_cells: 1
  parallel_groups: 1
  
  voltage_curve:
    100: 4.20
    95:  4.16
    90:  4.10
    85:  4.04
    80:  3.98
    75:  3.92
    70:  3.86
    65:  3.81
    60:  3.76
    55:  3.73
    50:  3.71  # Extended plateau
    45:  3.68
    40:  3.66
    35:  3.63
    30:  3.61
    25:  3.58
    20:  3.56
    15:  3.53
    10:  3.51
    5:   3.46
    0:   2.50
    
  discharge_curve:
    400:  1.00
    800:  0.98
    1600: 0.96
    3200: 0.91
    4000: 0.86
    
  temperature_coefficients:
    coefficient: -0.003
    reference_temp: 25.0
    
  safety_limits:
    max_voltage: 4.25
    min_voltage: 2.0
    max_current: 20000
    max_temperature: 60.0

# Dual 18650 Parallel Configuration
dual_18650_parallel:
  chemistry: "Li-ion"
  nominal_voltage: 3.7
  full_voltage: 4.2
  empty_voltage: 2.5
  capacity_mah: 5000  # 2x 2500mAh
  series_cells: 1
  parallel_groups: 2
  
  # Same voltage curve as single cell
  voltage_curve:
    100: 4.20
    95:  4.15
    90:  4.10
    85:  4.05
    80:  4.00
    75:  3.95
    70:  3.90
    65:  3.85
    60:  3.80
    55:  3.78
    50:  3.75
    45:  3.73
    40:  3.70
    35:  3.68
    30:  3.65
    25:  3.62
    20:  3.60
    15:  3.58
    10:  3.55
    5:   3.50
    0:   2.50
    
  # Higher current capability
  discharge_curve:
    500:  1.00   # C/10 total
    1000: 0.99   # C/5 total
    2000: 0.97   # C/2.5 total
    4000: 0.93   # C/1.25 total
    5000: 0.88   # 1C total
    
  temperature_coefficients:
    coefficient: -0.003
    reference_temp: 25.0
    
  safety_limits:
    max_voltage: 4.25
    min_voltage: 2.0
    max_current: 20000  # Higher total current
    max_temperature: 60.0

# Dual 18650 Series Configuration (7.4V System)
dual_18650_series:
  chemistry: "Li-ion"
  nominal_voltage: 7.4   # 2x 3.7V
  full_voltage: 8.4      # 2x 4.2V
  empty_voltage: 5.0     # 2x 2.5V
  capacity_mah: 2500
  series_cells: 2
  parallel_groups: 1
  
  # Double voltage curve
  voltage_curve:
    100: 8.40  # 2x 4.20V
    95:  8.30  # 2x 4.15V
    90:  8.20  # 2x 4.10V
    85:  8.10  # 2x 4.05V
    80:  8.00  # 2x 4.00V
    75:  7.90  # 2x 3.95V
    70:  7.80  # 2x 3.90V
    65:  7.70  # 2x 3.85V
    60:  7.60  # 2x 3.80V
    55:  7.56  # 2x 3.78V
    50:  7.50  # 2x 3.75V
    45:  7.46  # 2x 3.73V
    40:  7.40  # 2x 3.70V
    35:  7.36  # 2x 3.68V
    30:  7.30  # 2x 3.65V
    25:  7.24  # 2x 3.62V
    20:  7.20  # 2x 3.60V
    15:  7.16  # 2x 3.58V
    10:  7.10  # 2x 3.55V
    5:   7.00  # 2x 3.50V
    0:   5.00  # 2x 2.50V
    
  discharge_curve:
    250:  1.00
    500:  0.98
    1000: 0.95
    2000: 0.90
    2500: 0.85
    
  temperature_coefficients:
    coefficient: -0.006  # 2x single cell
    reference_temp: 25.0
    
  safety_limits:
    max_voltage: 8.50    # 2x 4.25V
    min_voltage: 4.0     # 2x 2.0V
    max_current: 10000
    max_temperature: 60.0

# Generic Lithium-Ion Profile (fallback)
generic_liion:
  chemistry: "Li-ion"
  nominal_voltage: 3.7
  full_voltage: 4.2
  empty_voltage: 3.0
  capacity_mah: 2000
  series_cells: 1
  parallel_groups: 1
  
  voltage_curve:
    100: 4.20
    90:  4.00
    80:  3.90
    70:  3.80
    60:  3.75
    50:  3.70
    40:  3.65
    30:  3.60
    20:  3.55
    10:  3.50
    5:   3.40
    0:   3.00
    
  discharge_curve:
    200:  1.00
    400:  0.98
    800:  0.95
    1600: 0.90
    2000: 0.85
    
  temperature_coefficients:
    coefficient: -0.003
    reference_temp: 25.0
    
  safety_limits:
    max_voltage: 4.25
    min_voltage: 2.5
    max_current: 8000
    max_temperature: 60.0

# Profile Selection Rules
profile_selection:
  # Automatic detection based on voltage range
  auto_detect:
    # Single cell (3-4.5V range)
    single_cell:
      voltage_range: [3.0, 4.5]
      default_profile: "18650_standard"
      
    # Dual cell series (6-9V range)
    dual_series:
      voltage_range: [6.0, 9.0]
      default_profile: "dual_18650_series"
      
    # Unknown range
    fallback:
      default_profile: "generic_liion"
  
  # Manual selection priority
  manual_override: true
  
  # Profile validation
  validation:
    require_monotonic_curve: true
    voltage_tolerance: 0.1  # 100mV tolerance
    capacity_range: [500, 10000]  # Valid capacity range in mAh

# Advanced Features
advanced_features:
  # Battery aging compensation
  aging_compensation:
    enabled: false
    cycle_count_tracking: true
    capacity_fade_rate: 0.02  # 2% per 100 cycles
    
  # Load-dependent curves
  load_dependent_curves:
    enabled: false
    load_thresholds: [0.5, 1.5]  # Low, medium, high load in Amps
    
  # Temperature derating
  temperature_derating:
    enabled: true
    derating_table:
      0:   0.80   # 80% capacity at 0°C
      10:  0.90   # 90% capacity at 10°C
      25:  1.00   # 100% capacity at 25°C
      40:  0.95   # 95% capacity at 40°C
      60:  0.85   # 85% capacity at 60°C

# Runtime Estimation Parameters
runtime_estimation:
  # Peukert's Law parameters
  peukert:
    enabled: true
    exponent: 1.1
    
  # System efficiency
  efficiency_factor: 0.95
  
  # Safety margin
  cutoff_margin: 0.1  # 10% margin before cutoff
  
  # Dynamic estimation
  dynamic_estimation:
    enabled: true
    history_window: 300  # 5 minutes of history
    load_averaging: true